# services:
#   app:
#     build: 
#       context: .
#       dockerfile: Dockerfile.cache-friendly
#       target: production
#     # ports:
#     #   - "3000:3000"
#     expose:
#       - 3000
#     environment:
#       - NODE_ENV=production
#       - DATABASE_URL=postgres://user:password@db:5432/mydb
#       - REDIS_URL=redis://redis:6379
#     depends_on:
#       db:
#         condition: service_healthy
#       redis:
#         condition: service_healthy

#   db:
#     image: postgres:17
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: mydb
#     volumes:
#       - pg_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#       start_period: 10s

#   redis:
#     image: redis:8-alpine
#     volumes:
#       - redis_data:/data
#     healthcheck:
#       test: ["CMD", "redis-cli", "ping"]
#       interval: 5s
#       timeout: 3s
#       retries: 5
#       start_period: 10s
#   nginx:
#     image: nginx:alpine
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       app:
#         condition: service_started

# volumes:
#   pg_data:
#   redis_data:

# services:
#   app:
#     image: my-app:prod

#     healthcheck:
#       test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
#       interval: 30s
#       timeout: 5s
#       retries: 3
#       start_period: 10s

#     env_file:
#       - .env

#     depends_on:
#       - db

#   db:
#     image: postgres:17

#     env_file:
#       - .env

#     secrets:
#       - db_password

#     environment:
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db_password

#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   redis:
#     image: redis:8-alpine

#     healthcheck:
#       test: ["CMD", "redis-cli", "ping"]
#       interval: 5s
#       timeout: 3s
#       retries: 5

#   nginx:
#     image: nginx:alpine

#     ports:
#       - "80:80"

#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf

#     depends_on:
#       - app

# secrets:
#   db_password:
#     external: true

services:
  app:
    build: .
    expose:
      - "3000"

    env_file:
      - .env

    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  redis:
    image: redis:8-alpine

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app